name: Test Pull Request
on: [pull_request]

jobs:
  unit-test:
    name: Run Unit Tests

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Get Source Code
        uses: actions/checkout@v3
      - name: Test
        run: make test
